name: altag
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.4
dependencies:
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  firebase_core: ^3.10.0
  firebase_database: ^11.3.0
  intl: ^0.19.0
  cloud_firestore: ^5.6.1
  url_launcher: ^6.3.1
  webauthn: ^0.2.5
  firebase_auth: ^5.4.1
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/ingredients/
flutter_intl:
  enabled: true
