name: altag
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.1

environment:
  sdk: ^3.5.4
dependencies:
  auto_exporter_annotation: ^1.0.1
  cloud_firestore: ^5.6.1
  cupertino_icons: ^1.0.8
  dev: ^1.0.0
  fake_cloud_firestore: ^3.1.0
  firebase_auth: ^5.4.1
  firebase_auth_mocks: ^0.14.1
  firebase_core: ^3.10.0
  firebase_database: ^11.3.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  hive_flutter: ^1.1.0
  home_widget: ^0.7.0+1
  intl: ^0.19.0
  mockito: ^5.4.4
  provider: ^6.1.2
  url_launcher: ^6.3.1
  webauthn: ^0.2.5

dev_dependencies:
  auto_exporter: ^3.3.0
  build_runner: ^2.4.13
  build_test: ^2.2.0
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  integration_test:
    sdk: flutter
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/appliances/
    - assets/ingredients/
    - assets/recipes/
flutter_intl:
  enabled: true
