name: Flutter Build Runner & Test Coverage

on: 
  push:
    branches:
      - main
      - develop
  pull_request:

jobs:
  build_runner_and_tests:
    runs-on: ubuntu-latest

    env:
      RUNNER_OS: macos

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.24.4"

      - name: Fix Flutter SDK folder permission
        run: |
          sudo chmod -R 777 /opt/hostedtoolcache/flutter

      - name: Install dependencies
        run: flutter pub get

      - name: Run Build Runner
        run: flutter pub run build_runner build --delete-conflicting-outputs

      - name: Verify No Uncommitted Changes
        run: |
          if [[ -n $(git status --porcelain) ]]; then
            echo "Build runner generated files differ! Please run build_runner locally and commit changes."
            exit 1
          fi

      - name: Run Tests with Coverage
        run: flutter test --coverage

      - name: Install lcov
        run: sudo apt-get install -y lcov

      - name: Remove Unwanted Coverage Files
        run: lcov --remove coverage/lcov.info 'lib/generated/*' 'lib/l10n/*' -o coverage/lcov.info

      - name: Generate HTML Coverage Report
        run: genhtml coverage/lcov.info -o coverage/html

      - name: Upload Coverage Report as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: coverage/html
