name: Deploy Flutter Web to Firebase Hosting

on:
  push:
    branches:
      - main  # Change this if your default branch is different

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    env:
      RUNNER_OS: macos  # Overrides the runner OS to avoid the Flutter version issue

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.24.4"  # Specify a known stable Flutter version

      # Fix Flutter SDK folder permission (in case of access issues)
      - name: Fix Flutter SDK folder permission
        run: |
          sudo chmod -R 777 /opt/hostedtoolcache/flutter

      - name: Install Dependencies
        run: flutter pub get

      - name: Build Flutter Web
        run: flutter build web --release

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Deploy to Firebase Hosting
        run: firebase deploy --only hosting --token "$FIREBASE_TOKEN"