name: Flutter Build Runner

on: 
  push:
    branches:
      - main
  pull_request:

jobs:
  build_runner:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.16.0'

      - name: Install dependencies
        run: flutter pub get

      - name: Run Build Runner
        run: flutter pub run build_runner build --delete-conflicting-outputs

      - name: Verify No Uncommitted Changes
        run: |
          if [[ -n $(git status --porcelain) ]]; then
            echo "Build runner generated files differ! Please run build_runner locally and commit changes."
            exit 1
          fi

      - name: Run Tests with Coverage
        run: flutter test --coverage

      - name: Install lcov
        run: sudo apt-get install -y lcov

      - name: Remove Unwanted Coverage Files
        run: lcov --remove coverage/lcov.info 'lib/generated/*' -o coverage/lcov.info

      - name: Generate HTML Coverage Report
        run: genhtml coverage/lcov.info -o coverage/html

      - name: Upload Coverage Report as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage/html