name: Deploy Flutter Web to Firebase Hosting

on:
  push:
    branches:
      - main  # Change this if your default branch is different

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    env:
      RUNNER_OS: macos

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.24.4"

      - name: Fix Flutter SDK folder permission
        run: |
          sudo chmod -R 777 /opt/hostedtoolcache/flutter

      - name: Install Dependencies
        run: flutter pub get

      - name: Build Flutter Web
        run: flutter build web --release

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Authenticate with Service Account
        run: |
          echo '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}' > $HOME/firebase-key.json
          export GOOGLE_APPLICATION_CREDENTIALS="$HOME/firebase-key.json"
      
      - name: Initialize Firebase Project
        run: firebase use altag

      - name: Deploy to Firebase Hosting
        run: firebase deploy --only hosting
